SECRET_KEY = 'not_a_secret'
CELERY_BROKER_URL='amqp://guest@localhost'
CELERY_RESULT_BACKEND='amqp://guest@localhost'
COUCHDB_SERVER = 'http://student:123@www.cscc01-team16.iriscouch.com/'
COUCHDB_DATABASE = 'p4_test_news_investigator'
